# docker build . -t my-php-app:1.0.0
FROM php:8.1-fpm
COPY ./src/ /app/
# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    nodejs \
    npm
# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer


# Set working directory
WORKDIR /app
ENV COMPOSER_ALLOW_SUPERUSER=1
RUN composer install
RUN chown -R 777 *
RUN npm install
RUN npm run development
USER root






